#!/bin/bash
set -e

DOCKER_IMG="dmd3c-img"

if [[ $# -eq 0 ]] ; then
  echo "WARNING: No arguments provided, image ${DOCKER_IMG} will be created"
else 
  DOCKER_IMG=$1
fi

PROJECT_ROOT="$(cd "$(dirname "$0")"; pwd)"

echo "----- Building Docker image from ${PROJECT_ROOT}/Dockerfile "
docker build -t ${DOCKER_IMG} ${PROJECT_ROOT}